data:extend({{
	type = "recipe",
	name = "sky-entrance",
	group = "surfaces",
	subgroup = "sky-access-shaft",
	enabled = true,
	ingredients = {
		{"wood", 40},
		{"copper-cable", 20},
	},
	result = "sky-entrance",
},{
	type = "recipe",
	name = "sky-entrance-2",
	group = "surfaces",
	subgroup = "sky-access-shaft",
	enabled = true,
	ingredients = {{"sky-exit", 1}},
	result = "sky-entrance",
},{
	type = "recipe",
	name = "sky-entrance-3",
	group = "surfaces",
	subgroup = "sky-access-shaft",
	enabled = true,
	ingredients = {{"underground-exit", 1}},
	result = "sky-entrance",
},{
	type = "recipe",
	name = "sky-exit",
	group = "surfaces",
	subgroup = "sky-access-shaft",
	enabled = true,
	ingredients = {
		{"wood", 40},
		{"copper-cable", 20},
	},
	result = "sky-exit",
},{
	type = "recipe",
	name = "sky-exit-2",
	group = "surfaces",
	subgroup = "sky-access-shaft",
	enabled = true,
	ingredients = {{"sky-entrance", 1}},
	result = "sky-exit",
},{
	type = "recipe",
	name = "sky-exit-3",
	group = "surfaces",
	subgroup = "sky-access-shaft",
	enabled = true,
	ingredients = {{"underground-entrance", 1}},
	result = "sky-exit",
}})