data:extend({{
	type = "recipe",
	name = "underground-exit",
	group = "surfaces",
	subgroup = "underground-access-shaft",
	enabled = true,
	ingredients = {
		{"wood", 40},
		{"copper-cable", 20},
	},
	result = "underground-exit",
},{
	type = "recipe",
	name = "underground-exit-2",
	group = "surfaces",
	subgroup = "underground-access-shaft",
	enabled = true,
	ingredients = {{"underground-entrance", 1}},
	result = "underground-exit",
},{
	type = "recipe",
	name = "underground-exit-3",
	group = "surfaces",
	subgroup = "underground-access-shaft",
	enabled = true,
	ingredients = {{"sky-entrance", 1}},
	result = "underground-exit",
},{
	type = "recipe",
	name = "underground-entrance",
	group = "surfaces",
	subgroup = "underground-access-shaft",
	enabled = true,
	ingredients = {
		{"wood", 40},
		{"copper-cable", 20},
	},
	result = "underground-entrance",
},{
	type = "recipe",
	name = "underground-entrance-2",
	group = "surfaces",
	subgroup = "underground-access-shaft",
	enabled = true,
	ingredients = {{"underground-exit", 1}},
	result = "underground-entrance",
},{
	type = "recipe",
	name = "underground-entrance-3",
	group = "surfaces",
	subgroup = "underground-access-shaft",
	enabled = true,
	ingredients = {{"sky-exit", 1}},
	result = "underground-entrance",
}})