require("script.proto")

local small_lower = proto.get({"item", "electric_pole", "small"}, "lower", true)
local small_upper = proto.get({"item", "electric_pole", "small"}, "upper", true)
local medium_lower = proto.get({"item", "electric_pole", "medium"}, "lower", true)
local medium_upper = proto.get({"item", "electric_pole", "medium"}, "upper", true)
local big_lower = proto.get({"item", "electric_pole", "big"}, "lower", true)
local big_upper = proto.get({"item", "electric_pole", "big"}, "upper", true)
local substation_lower = proto.get({"item", "electric_pole", "substation"}, "lower", true)
local substation_upper = proto.get({"item", "electric_pole", "substation"}, "upper", true)
small_lower.place_result = proto.get_field({"entity", "electric_pole", "small", "lower"}, "name")
small_upper.place_result = proto.get_field({"entity", "electric_pole", "small", "upper"}, "name")
medium_lower.place_result = proto.get_field({"entity", "electric_pole", "medium", "lower"}, "name")
medium_upper.place_result = proto.get_field({"entity", "electric_pole", "medium", "upper"}, "name")
big_lower.place_result = proto.get_field({"entity", "electric_pole", "big", "lower"}, "name")
big_upper.place_result = proto.get_field({"entity", "electric_pole", "big", "upper"}, "name")
substation_lower.place_result = proto.get_field({"entity", "electric_pole", "substation", "lower"}, "name")
substation_upper.place_result = proto.get_field({"entity", "electric_pole", "substation", "upper"}, "name")

data:extend({small_lower, small_upper, medium_lower, medium_upper, big_lower, big_upper, substation_lower, substation_upper})